version: '3'

services:
  web:
    command: >
      bash -c "
        # Run test server
        RAILS_ENV=test puma -b tcp://0.0.0.0:3001
        "
    expose: [3001]

  selenium:
    expose: [4444, 5900]
